name: whiteboard_demo
description: DrawnOut - Interactive whiteboard learning platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1
  file_picker: ^10.3.10
  opencv_dart: ^1.4.3
  http: ^1.2.1
  just_audio: ^0.10.5
  
  # Auth and state management
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
